# SPDX-License-Identifier: BSD-3-Clause
from nmigen       import *


_PS8_TEST_SIGNALS = {
	'o_DBGPATHFIFOBYPASS': Signal(),


	'i_FMIOCHARAFIFSFPDTESTINPUT':   Signal(),
	'o_FMIOCHARAFIFSFPDTESTOUTPUT':  Signal(),
	'i_FMIOCHARAFIFSFPDTESTSELECTN': Signal(),


	'i_FMIOCHARAFIFSLPDTESTINPUT':   Signal(),
	'o_FMIOCHARAFIFSLPDTESTOUTPUT':  Signal(),
	'i_FMIOCHARAFIFSLPDTESTSELECTN': Signal(),


	'i_FMIOCHARGEMSELECTION':   Signal(2),
	'i_FMIOCHARGEMTESTINPUT':   Signal(),
	'o_FMIOCHARGEMTESTOUTPUT':  Signal(),
	'i_FMIOCHARGEMTESTSELECTN': Signal(),


	'i_FMIOSD0DLLTESTINN': Signal(4),
	'o_FMIOSD0DLLTESTOUT': Signal(8),


	'i_FMIOSD1DLLTESTINN': Signal(4),
	'o_FMIOSD1DLLTESTOUT': Signal(8),


	'i_FMIOTESTGEMSCANMUX1': Signal(),
	'i_FMIOTESTGEMSCANMUX2': Signal(),


	'i_FMIOTESTIOCHARSCANCLOCK':  Signal(),
	'i_FMIOTESTIOCHARSCANENABLE': Signal(),
	'i_FMIOTESTIOCHARSCANIN':     Signal(),
	'o_FMIOTESTIOCHARSCANOUT':    Signal(),
	'i_FMIOTESTIOCHARSCANRESETN': Signal(),


	'i_FMIOTESTQSPISCANMUX1N': Signal(),


	'i_FMIOTESTSDIOSCANMUX1': Signal(),
	'i_FMIOTESTSDIOSCANMUX2': Signal(),


	'o_FPDPLLTESTOUT': Signal(32),


	'o_FPDPLSPARE0OUT': Signal(),
	'o_FPDPLSPARE1OUT': Signal(),
	'o_FPDPLSPARE2OUT': Signal(),
	'o_FPDPLSPARE3OUT': Signal(),
	'o_FPDPLSPARE4OUT': Signal(),


	'i_IAFECMNBGENABLELOWLEAKAGE':    Signal(),
	'i_IAFECMNBGISOCTRLBAR':          Signal(),
	'i_IAFECMNBGPD':                  Signal(),
	'i_IAFECMNBGPDBGOK':              Signal(),
	'i_IAFECMNBGPDPTAT':              Signal(),
	'i_IAFECMNCALIBENABLELOWLEAKAGE': Signal(),
	'i_IAFECMNCALIBENICONST':         Signal(),
	'i_IAFECMNCALIBISOCTRLBAR':       Signal(),


	'i_IAFEMODE': Signal(),


	'i_IAFEPLLCOARSECODE':    Signal(11),
	'i_IAFEPLLENCLOCKHSDIV2': Signal(),
	'i_IAFEPLLFBDIV':         Signal(16),
	'i_IAFEPLLLOADFBDIV':     Signal(),
	'i_IAFEPLLPD':            Signal(),
	'i_IAFEPLLPDHSCLOCKR':    Signal(),
	'i_IAFEPLLPDPFD':         Signal(),
	'i_IAFEPLLRSTFDBKDIV':    Signal(),
	'i_IAFEPLLSTARTLOOP':     Signal(),
	'i_IAFEPLLV2ICODE':       Signal(6),
	'i_IAFEPLLV2IPROG':       Signal(5),
	'i_IAFEPLLVCOCNTWINDOW':  Signal(),


	'i_IAFERXHSRXCLOCKSTOPREQ':                   Signal(),
	'i_IAFERXISOHSRXCTRLBAR':                     Signal(),
	'i_IAFERXISOLFPSCTRLBAR':                     Signal(),
	'i_IAFERXISOSIGDETCTRLBAR':                   Signal(),
	'i_IAFERXMPHYGATESYMBOLCLK':                  Signal(),
	'i_IAFERXMPHYMUXHSBLS':                       Signal(),
	'i_IAFERXPIPERXEQTRAINING':                   Signal(),
	'i_IAFERXPIPERXTERMENABLE':                   Signal(),
	'i_IAFERXRXPMAREFCLKDIG':                     Signal(),
	'i_IAFERXRXPMARSTB':                          Signal(),
	'i_IAFERXSYMBOLCLKBY2PL':                     Signal(),
	'i_IAFERXUPHYBIASGENICONSTCOREMIRRORENABLE':  Signal(),
	'i_IAFERXUPHYBIASGENICONSTIOMIRRORENABLE':    Signal(),
	'i_IAFERXUPHYBIASGENIRCONSTCOREMIRRORENABLE': Signal(),
	'i_IAFERXUPHYENABLECDR':                      Signal(),
	'i_IAFERXUPHYENABLELOWLEAKAGE':               Signal(),
	'i_IAFERXUPHYHSCLKDIVISIONFACTOR':            Signal(2),
	'i_IAFERXUPHYHSRXRSTB':                       Signal(),
	'i_IAFERXUPHYPDNHSDES':                       Signal(),
	'i_IAFERXUPHYPDSAMPC2C':                      Signal(),
	'i_IAFERXUPHYPDSAMPC2CECLK':                  Signal(),
	'i_IAFERXUPHYPSOCLKLANE':                     Signal(),
	'i_IAFERXUPHYPSOEQ':                          Signal(),
	'i_IAFERXUPHYPSOHSRXDIG':                     Signal(),
	'i_IAFERXUPHYPSOIQPI':                        Signal(),
	'i_IAFERXUPHYPSOLFPSBCN':                     Signal(),
	'i_IAFERXUPHYPSOSAMPFLOPS':                   Signal(),
	'i_IAFERXUPHYPSOSIGDET':                      Signal(),
	'i_IAFERXUPHYRESTORECALCODE':                 Signal(),
	'i_IAFERXUPHYRESTORECALCODEDATA':             Signal(8),
	'i_IAFERXUPHYRUNCALIB':                       Signal(),
	'i_IAFERXUPHYRXLANEPOLARITYSWAP':             Signal(),
	'i_IAFERXUPHYRXPMAOPMODE':                    Signal(8),
	'i_IAFERXUPHYSTARTLOOPPLL':                   Signal(),


	'i_IAFETXANAIFRATE':               Signal(2),
	'i_IAFETXENABLEHSCLKDIVISION':     Signal(2),
	'i_IAFETXENABLELDO':               Signal(),
	'i_IAFETXENABLEREF':               Signal(),
	'i_IAFETXENABLESUPPLYHSCLK':       Signal(),
	'i_IAFETXENABLESUPPLYPIPE':        Signal(),
	'i_IAFETXENABLESUPPLYSERIALIZER':  Signal(),
	'i_IAFETXENABLESUPPLYUPHY':        Signal(),
	'i_IAFETXENDIGSUBLPMODE':          Signal(),
	'i_IAFETXHSSERRSTB':               Signal(),
	'i_IAFETXHSSYMBOL':                Signal(20),
	'i_IAFETXISOCTRLBAR':              Signal(),
	'i_IAFETXLFPSCLK':                 Signal(),
	'i_IAFETXLPBKSEL':                 Signal(3),
	'i_IAFETXMPHYTXLSDATA':            Signal(),
	'i_IAFETXPIPETXENABLEIDLEMODE':    Signal(2),
	'i_IAFETXPIPETXENABLELFPS':        Signal(2),
	'i_IAFETXPIPETXENABLERXDET':       Signal(),
	'i_IAFETXPIPETXFASTESTCOMMONMODE': Signal(),
	'i_IAFETXPLLSYMBCLK2':             Signal(),
	'i_IAFETXPMADIGDIGITALRESETN':     Signal(),
	'i_IAFETXSERIALIZERRSTB':          Signal(),
	'i_IAFETXSERIALIZERRSTREL':        Signal(),
	'i_IAFETXSERISOCTRLBAR':           Signal(),
	'i_IAFETXUPHYTXPMAOPMODE':         Signal(8),


	'i_IBGCALAFEMODE': Signal(),


	'i_IDBGL0RXCLK': Signal(),
	'i_IDBGL0TXCLK': Signal(),
	'i_IDBGL1RXCLK': Signal(),
	'i_IDBGL1TXCLK': Signal(),
	'i_IDBGL2RXCLK': Signal(),
	'i_IDBGL2TXCLK': Signal(),
	'i_IDBGL3RXCLK': Signal(),
	'i_IDBGL3TXCLK': Signal(),


	'i_IOCHARAUDIOINTESTDATA':  Signal(),
	'i_IOCHARAUDIOMUXSELN':     Signal(),
	'o_IOCHARAUDIOOUTTESTDATA': Signal(),


	'i_IOCHARVIDEOINTESTDATA':  Signal(),
	'i_IOCHARVIDEOMUXSELN':     Signal(),
	'o_IOCHARVIDEOOUTTESTDATA': Signal(),


	'i_IPLLAFEMODE': Signal(),


	'o_LPDPLLTESTOUT': Signal(32),


	'o_LPDPLSPARE0OUT': Signal(),
	'o_LPDPLSPARE1OUT': Signal(),
	'o_LPDPLSPARE2OUT': Signal(),
	'o_LPDPLSPARE3OUT': Signal(),
	'o_LPDPLSPARE4OUT': Signal(),


	'o_OAFECMNCALIBCOMPOUT':         Signal(),
	'o_OAFEPGAVDDCR':                Signal(),
	'o_OAFEPGAVDDIO':                Signal(),
	'o_OAFEPGDVDDCR':                Signal(),
	'o_OAFEPGSTATICAVDDCR':          Signal(),
	'o_OAFEPGSTATICAVDDIO':          Signal(),
	'o_OAFEPLLCLKSYMHS':             Signal(),
	'o_OAFEPLLDCOCOUNT':             Signal(13),
	'o_OAFEPLLFBCLKFRAC':            Signal(),
	'o_OAFERXHSRXCLOCKSTOPACK':      Signal(),
	'o_OAFERXPIPELFPSBCNRXELECIDLE': Signal(),
	'o_OAFERXPIPESIGDET':            Signal(),
	'o_OAFERXSYMBOL':                Signal(20),
	'o_OAFERXSYMBOLCLKBY2':          Signal(),
	'o_OAFERXUPHYRXCALIBDONE':       Signal(),
	'o_OAFERXUPHYSAVECALCODE':       Signal(),
	'o_OAFERXUPHYSAVECALCODEDATA':   Signal(8),
	'o_OAFERXUPHYSTARTLOOPBUF':      Signal(),
	'o_OAFETXDIGRESETRELACK':        Signal(),
	'o_OAFETXPIPETXDNRXDET':         Signal(),
	'o_OAFETXPIPETXDPRXDET':         Signal(),


	'o_ODBGL0PHYSTATUS':           Signal(),
	'o_ODBGL0POWERDOWN':           Signal(2),
	'o_ODBGL0RATE':                Signal(2),
	'o_ODBGL0RSTB':                Signal(),
	'o_ODBGL0RXCLK':               Signal(),
	'o_ODBGL0RXDATA':              Signal(20),
	'o_ODBGL0RXDATAK':             Signal(2),
	'o_ODBGL0RXELECIDLE':          Signal(),
	'o_ODBGL0RXPOLARITY':          Signal(),
	'o_ODBGL0RXSGMIIENCDET':       Signal(),
	'o_ODBGL0RXSTATUS':            Signal(3),
	'o_ODBGL0RXVALID':             Signal(),
	'o_ODBGL0SATACORECLOCKREADY':  Signal(),
	'o_ODBGL0SATACOREREADY':       Signal(),
	'o_ODBGL0SATACORERXDATA':      Signal(20),
	'o_ODBGL0SATACORERXDATAVALID': Signal(2),
	'o_ODBGL0SATACORERXSIGNALDET': Signal(),
	'o_ODBGL0SATAPHYCTRLPARTIAL':  Signal(),
	'o_ODBGL0SATAPHYCTRLRESET':    Signal(),
	'o_ODBGL0SATAPHYCTRLRXRATE':   Signal(2),
	'o_ODBGL0SATAPHYCTRLRXRST':    Signal(),
	'o_ODBGL0SATAPHYCTRLSLUMBER':  Signal(),
	'o_ODBGL0SATAPHYCTRLTXDATA':   Signal(20),
	'o_ODBGL0SATAPHYCTRLTXIDLE':   Signal(),
	'o_ODBGL0SATAPHYCTRLTXRATE':   Signal(2),
	'o_ODBGL0SATAPHYCTRLTXRST':    Signal(),
	'o_ODBGL0TXCLK':               Signal(),
	'o_ODBGL0TXDATA':              Signal(20),
	'o_ODBGL0TXDATAK':             Signal(2),
	'o_ODBGL0TXDETRXLPBACK':       Signal(),
	'o_ODBGL0TXELECIDLE':          Signal(),
	'o_ODBGL0TXSGMIIEWRAP':        Signal(),


	'o_ODBGL1PHYSTATUS':           Signal(),
	'o_ODBGL1POWERDOWN':           Signal(2),
	'o_ODBGL1RATE':                Signal(2),
	'o_ODBGL1RSTB':                Signal(),
	'o_ODBGL1RXCLK':               Signal(),
	'o_ODBGL1RXDATA':              Signal(20),
	'o_ODBGL1RXDATAK':             Signal(2),
	'o_ODBGL1RXELECIDLE':          Signal(),
	'o_ODBGL1RXPOLARITY':          Signal(),
	'o_ODBGL1RXSGMIIENCDET':       Signal(),
	'o_ODBGL1RXSTATUS':            Signal(3),
	'o_ODBGL1RXVALID':             Signal(),
	'o_ODBGL1SATACORECLOCKREADY':  Signal(),
	'o_ODBGL1SATACOREREADY':       Signal(),
	'o_ODBGL1SATACORERXDATA':      Signal(20),
	'o_ODBGL1SATACORERXDATAVALID': Signal(2),
	'o_ODBGL1SATACORERXSIGNALDET': Signal(),
	'o_ODBGL1SATAPHYCTRLPARTIAL':  Signal(),
	'o_ODBGL1SATAPHYCTRLRESET':    Signal(),
	'o_ODBGL1SATAPHYCTRLRXRATE':   Signal(2),
	'o_ODBGL1SATAPHYCTRLRXRST':    Signal(),
	'o_ODBGL1SATAPHYCTRLSLUMBER':  Signal(),
	'o_ODBGL1SATAPHYCTRLTXDATA':   Signal(20),
	'o_ODBGL1SATAPHYCTRLTXIDLE':   Signal(),
	'o_ODBGL1SATAPHYCTRLTXRATE':   Signal(2),
	'o_ODBGL1SATAPHYCTRLTXRST':    Signal(),
	'o_ODBGL1TXCLK':               Signal(),
	'o_ODBGL1TXDATA':              Signal(20),
	'o_ODBGL1TXDATAK':             Signal(2),
	'o_ODBGL1TXDETRXLPBACK':       Signal(),
	'o_ODBGL1TXELECIDLE':          Signal(),
	'o_ODBGL1TXSGMIIEWRAP':        Signal(),


	'o_ODBGL2PHYSTATUS':           Signal(),
	'o_ODBGL2POWERDOWN':           Signal(2),
	'o_ODBGL2RATE':                Signal(2),
	'o_ODBGL2RSTB':                Signal(),
	'o_ODBGL2RXCLK':               Signal(),
	'o_ODBGL2RXDATA':              Signal(20),
	'o_ODBGL2RXDATAK':             Signal(2),
	'o_ODBGL2RXELECIDLE':          Signal(),
	'o_ODBGL2RXPOLARITY':          Signal(),
	'o_ODBGL2RXSGMIIENCDET':       Signal(),
	'o_ODBGL2RXSTATUS':            Signal(3),
	'o_ODBGL2RXVALID':             Signal(),
	'o_ODBGL2SATACORECLOCKREADY':  Signal(),
	'o_ODBGL2SATACOREREADY':       Signal(),
	'o_ODBGL2SATACORERXDATA':      Signal(20),
	'o_ODBGL2SATACORERXDATAVALID': Signal(2),
	'o_ODBGL2SATACORERXSIGNALDET': Signal(),
	'o_ODBGL2SATAPHYCTRLPARTIAL':  Signal(),
	'o_ODBGL2SATAPHYCTRLRESET':    Signal(),
	'o_ODBGL2SATAPHYCTRLRXRATE':   Signal(2),
	'o_ODBGL2SATAPHYCTRLRXRST':    Signal(),
	'o_ODBGL2SATAPHYCTRLSLUMBER':  Signal(),
	'o_ODBGL2SATAPHYCTRLTXDATA':   Signal(20),
	'o_ODBGL2SATAPHYCTRLTXIDLE':   Signal(),
	'o_ODBGL2SATAPHYCTRLTXRATE':   Signal(2),
	'o_ODBGL2SATAPHYCTRLTXRST':    Signal(),
	'o_ODBGL2TXCLK':               Signal(),
	'o_ODBGL2TXDATA':              Signal(20),
	'o_ODBGL2TXDATAK':             Signal(2),
	'o_ODBGL2TXDETRXLPBACK':       Signal(),
	'o_ODBGL2TXELECIDLE':          Signal(),
	'o_ODBGL2TXSGMIIEWRAP':        Signal(),

	'o_ODBGL3PHYSTATUS':           Signal(),
	'o_ODBGL3POWERDOWN':           Signal(2),
	'o_ODBGL3RATE':                Signal(2),
	'o_ODBGL3RSTB':                Signal(),
	'o_ODBGL3RXCLK':               Signal(),
	'o_ODBGL3RXDATA':              Signal(20),
	'o_ODBGL3RXDATAK':             Signal(2),
	'o_ODBGL3RXELECIDLE':          Signal(),
	'o_ODBGL3RXPOLARITY':          Signal(),
	'o_ODBGL3RXSGMIIENCDET':       Signal(),
	'o_ODBGL3RXSTATUS':            Signal(3),
	'o_ODBGL3RXVALID':             Signal(),
	'o_ODBGL3SATACORECLOCKREADY':  Signal(),
	'o_ODBGL3SATACOREREADY':       Signal(),
	'o_ODBGL3SATACORERXDATA':      Signal(20),
	'o_ODBGL3SATACORERXDATAVALID': Signal(2),
	'o_ODBGL3SATACORERXSIGNALDET': Signal(),
	'o_ODBGL3SATAPHYCTRLPARTIAL':  Signal(),
	'o_ODBGL3SATAPHYCTRLRESET':    Signal(),
	'o_ODBGL3SATAPHYCTRLRXRATE':   Signal(2),
	'o_ODBGL3SATAPHYCTRLRXRST':    Signal(),
	'o_ODBGL3SATAPHYCTRLSLUMBER':  Signal(),
	'o_ODBGL3SATAPHYCTRLTXDATA':   Signal(20),
	'o_ODBGL3SATAPHYCTRLTXIDLE':   Signal(),
	'o_ODBGL3SATAPHYCTRLTXRATE':   Signal(2),
	'o_ODBGL3SATAPHYCTRLTXRST':    Signal(),
	'o_ODBGL3TXCLK':               Signal(),
	'o_ODBGL3TXDATA':              Signal(20),
	'o_ODBGL3TXDATAK':             Signal(2),
	'o_ODBGL3TXDETRXLPBACK':       Signal(),
	'o_ODBGL3TXELECIDLE':          Signal(),
	'o_ODBGL3TXSGMIIEWRAP':        Signal(),


	'i_PLFPDPLLTESTCKSELN':       Signal(3),
	'i_PLFPDPLLTESTFRACTCLKSELN': Signal(),
	'i_PLFPDPLLTESTFRACTENN':     Signal(),
	'i_PLFPDPLLTESTMUXSEL':       Signal(2),
	'i_PLFPDPLLTESTSEL':          Signal(4),
	'i_PLFPDSPARE0IN':            Signal(),
	'i_PLFPDSPARE1IN':            Signal(),
	'i_PLFPDSPARE2IN':            Signal(),
	'i_PLFPDSPARE3IN':            Signal(),
	'i_PLFPDSPARE4IN':            Signal(),
	'i_PLFPGASTOP':               Signal(4),


	'i_PLLAUXREFCLKFPD':          Signal(3),
	'i_PLLAUXREFCLKLPD':          Signal(2),
	'i_PLLPDPLLTESTCKSELN':       Signal(3),
	'i_PLLPDPLLTESTFRACTCLKSELN': Signal(),
	'i_PLLPDPLLTESTFRACTENN':     Signal(),
	'i_PLLPDPLLTESTMUXSEL':       Signal(),
	'i_PLLPDPLLTESTSEL':          Signal(4),
	'i_PLLPDSPARE0IN':            Signal(),
	'i_PLLPDSPARE1IN':            Signal(),
	'i_PLLPDSPARE2IN':            Signal(),
	'i_PLLPDSPARE3IN':            Signal(),
	'i_PLLPDSPARE4IN':            Signal(),


	'i_PSTPPLCLK': Signal(4),
	'i_PSTPPLIN':  Signal(32),
	'o_PSTPPLOUT': Signal(32),
	'i_PSTPPLTS':  Signal(32),


	'i_TESTADC2IN': Signal(32),
	'i_TESTADCCLK': Signal(4),
	'i_TESTADCIN':  Signal(32),
	'o_TESTADCOUT': Signal(20),
	'o_TESTAMSOSC': Signal(8),


	'i_TESTBSCANACMODE':       Signal(),
	'i_TESTBSCANACTEST':       Signal(),
	'i_TESTBSCANCLOCKDR':      Signal(),
	'i_TESTBSCANENN':          Signal(),
	'i_TESTBSCANEXTEST':       Signal(),
	'i_TESTBSCANINITMEMORY':   Signal(),
	'i_TESTBSCANINTEST':       Signal(),
	'i_TESTBSCANMISRJTAGLOAD': Signal(),
	'i_TESTBSCANMODEC':        Signal(),
	'i_TESTBSCANRESETTAPB':    Signal(),
	'i_TESTBSCANSHIFTDR':      Signal(),
	'i_TESTBSCANTDI':          Signal(),
	'i_TESTBSCANTDO':          Signal(),
	'i_TESTBSCANUPDATEDR':     Signal(),


	'i_TESTCHARMODEFPDN':     Signal(),
	'i_TESTCHARMODELPDN':     Signal(),
	'i_TESTCONVST':           Signal(),
	'i_TESTDADDR':            Signal(8),
	'o_TESTDB':               Signal(16),
	'i_TESTDCLK':             Signal(),
	'o_TESTDDR2PLDCDSKEWOUT': Signal(),
	'i_TESTDEN':              Signal(),
	'i_TESTDI':               Signal(16),
	'o_TESTDO':               Signal(16),
	'o_TESTDRDY':             Signal(),
	'i_TESTDWE':              Signal(),
	'o_TESTMONDATA':          Signal(16),


	'i_TESTPL2DDRDCDSAMPLEPULSE': Signal(),


	'o_TESTPLPLLLOCKOUT': Signal(5),


	'i_TESTPLSCANCHOPPERSI':   Signal(),
	'o_TESTPLSCANCHOPPERSO':   Signal(),
	'i_TESTPLSCANCHOPPERTRIG': Signal(),
	'i_TESTPLSCANCLK0':        Signal(),
	'i_TESTPLSCANCLK1':        Signal(),
	'i_TESTPLSCANEDTCLK':      Signal(),
	'i_TESTPLSCANEDTINAPU':    Signal(),
	'i_TESTPLSCANEDTINCPU':    Signal(),
	'i_TESTPLSCANEDTINDDR':    Signal(4),
	'i_TESTPLSCANEDTINFP':     Signal(10),
	'i_TESTPLSCANEDTINGPU':    Signal(4),
	'i_TESTPLSCANEDTINLP':     Signal(9),
	'i_TESTPLSCANEDTINUSB3':   Signal(2),


	'o_TESTPLSCANEDTOUTAPU':      Signal(),
	'o_TESTPLSCANEDTOUTCPU0':     Signal(),
	'o_TESTPLSCANEDTOUTCPU1':     Signal(),
	'o_TESTPLSCANEDTOUTCPU2':     Signal(),
	'o_TESTPLSCANEDTOUTCPU3':     Signal(),
	'o_TESTPLSCANEDTOUTDDR':      Signal(4),
	'o_TESTPLSCANEDTOUTFP':       Signal(10),
	'o_TESTPLSCANEDTOUTGPU':      Signal(4),
	'o_TESTPLSCANEDTOUTLP':       Signal(9),
	'o_TESTPLSCANEDTOUTUSB3':     Signal(2),
	'i_TESTPLSCANEDTUPDATE':      Signal(),
	'i_TESTPLSCANENABLE':         Signal(),
	'i_TESTPLSCANENABLESLCREN':   Signal(),
	'i_TESTPLSCANPLLRESET':       Signal(),
	'i_TESTPLSCANRESETN':         Signal(),
	'i_TESTPLSCANSLCRCONFIGCLK':  Signal(),
	'i_TESTPLSCANSLCRCONFIGRSTN': Signal(),
	'i_TESTPLSCANSLCRCONFIGSI':   Signal(),
	'o_TESTPLSCANSLCRCONFIGSO':   Signal(),
	'i_TESTPLSCANSPAREIN0':       Signal(),
	'i_TESTPLSCANSPAREIN1':       Signal(),
	'i_TESTPLSCANSPAREIN2':       Signal(),
	'o_TESTPLSCANSPAREOUT0':      Signal(),
	'o_TESTPLSCANSPAREOUT1':      Signal(),
	'i_TESTPLSCANWRAPCLK':        Signal(),
	'i_TESTPLSCANWRAPISHIFT':     Signal(),
	'i_TESTPLSCANWRAPOSHIFT':     Signal(),


	'i_TESTUSB0FUNCMUX0N': Signal(),
	'i_TESTUSB0SCANMUX0N': Signal(),


	'i_TESTUSB1FUNCMUX0N': Signal(),
	'i_TESTUSB1SCANMUX0N': Signal(),


	'i_TSTRTCCALIBREGIN':  Signal(21),
	'o_TSTRTCCALIBREGOUT': Signal(21),
	'i_TSTRTCCALIBREGWE':  Signal(),


	'i_TSTRTCCLK':          Signal(),
	'i_TSTRTCDISABLEBATOP': Signal(),


	'o_TSTRTCOSCCLKOUT':   Signal(),
	'i_TSTRTCOSCCNTRLIN':  Signal(4),
	'o_TSTRTCOSCCNTRLOUT': Signal(4),
	'i_TSTRTCOSCCNTRLWE':  Signal(),


	'o_TSTRTCSECCOUNTEROUT':    Signal(32),
	'o_TSTRTCSECONDSRAWINT':    Signal(),
	'i_TSTRTCSECRELOAD':        Signal(),
	'i_TSTRTCTESTCLOCKSELECTN': Signal(),
	'i_TSTRTCTESTMODEN':        Signal(),
	'o_TSTRTCTICKCOUNTEROUT':   Signal(16),
	'i_TSTRTCTIMESETREGIN':     Signal(32),
	'o_TSTRTCTIMESETREGOUT':    Signal(32),
	'i_TSTRTCTIMESETREGWE':     Signal(),
}
