name: "Vivado Test"
on:
  push:
    branches:
      - 'main'
jobs:
  synth:
    runs-on: self-hosted
    steps:
      - name: Initialize Envrionment
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=\"`pwd`\"" >> $GITHUB_ENV
          echo "NMIGEN_ENV_Vivado=/opt/Xilinx/Vivado/2021.1/settings64.sh" >> $GITHUB_ENV
          echo "NMIGEN_USE_YOSYS=builtin" >> $GITHUB_ENV
          echo "YOSYS=yowasp-yosys" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        shell: bash
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libncurses5
          sudo pip3 install --upgrade pip setuptools wheel yowasp-yosys nmigen-yosys
          pip3 install --user -r ./docs/requirements.txt
          pip3 install --user -e .
      - name: Synth PS8
        shell: bash
        run: |
          python3 ./examples/xilinx/ps8_k26c.py 
